/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package website;

import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author Cintaku
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        scaleImage();
    }
    public void scaleImage()
    {
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/9295993 (1).png"));
        Image img = icon.getImage();
        Image imgScale2 = img.getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon2 = new ImageIcon(imgScale2);
        background.setIcon(scaledIcon2);       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        error6 = new javax.swing.JLabel();
        error5 = new javax.swing.JLabel();
        error4 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        femail = new javax.swing.JTextField();
        fusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fpass = new javax.swing.JPasswordField();
        fgender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        faddress = new javax.swing.JTextField();
        fstate = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error6.setForeground(new java.awt.Color(255, 0, 0));
        error6.setText(" ");
        jPanel1.add(error6, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 143, 220, 20));

        error5.setForeground(new java.awt.Color(255, 0, 0));
        error5.setText(" ");
        jPanel1.add(error5, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 223, 220, 20));

        error4.setForeground(new java.awt.Color(255, 0, 0));
        error4.setText(" ");
        jPanel1.add(error4, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 303, 220, 20));

        error3.setForeground(new java.awt.Color(255, 0, 0));
        error3.setText(" ");
        jPanel1.add(error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 263, 220, 20));

        error2.setForeground(new java.awt.Color(255, 0, 0));
        error2.setText(" ");
        jPanel1.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 183, 220, 20));

        error1.setForeground(new java.awt.Color(255, 0, 0));
        error1.setText(" ");
        jPanel1.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 103, 290, 20));

        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setText(" ");
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 63, 220, 20));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("State:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 119, -1, 25));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 79, -1, 25));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("Gender:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 199, -1, 25));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 279, -1, 25));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 239, -1, 25));

        femail.setToolTipText("Enter email");
        femail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femailActionPerformed(evt);
            }
        });
        jPanel1.add(femail, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 80, 230, -1));

        fusername.setToolTipText("Enter a Username");
        fusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fusernameActionPerformed(evt);
            }
        });
        jPanel1.add(fusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 240, 230, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setText("Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 40, -1, 25));

        fname.setToolTipText("Enter name");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 40, 230, -1));

        jButton1.setBackground(new java.awt.Color(255, 177, 95));
        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jButton1.setText("Register");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 349, 280, -1));

        fpass.setToolTipText("Enter a secured password");
        fpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpassActionPerformed(evt);
            }
        });
        jPanel1.add(fpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 280, 230, -1));

        fgender.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say", "Non-Binary" }));
        jPanel1.add(fgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 200, 130, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setText("Address:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 159, -1, 25));

        faddress.setToolTipText("Enter current address");
        faddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faddressActionPerformed(evt);
            }
        });
        jPanel1.add(faddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 160, 230, -1));

        fstate.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        fstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akwa Ibom State", "Calabar", "Cross River" }));
        fstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fstateActionPerformed(evt);
            }
        });
        jPanel1.add(fstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 120, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 90, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9295993 (1).png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void faddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faddressActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {

            String name = fname.getText().trim();
            String email = femail.getText().toLowerCase().trim();
            String state = (String) fstate.getSelectedItem();
            String address = faddress.getText().trim();
            String sex = (String) fgender.getSelectedItem();
            String username = fusername.getText().trim();
            String password = fpass.getText();
            
            boolean hr = false;
            
            if(name.isEmpty())
            {
                error.setText("Name required");
                hr=true;
            }
            
            else
            {
                error.setText("");
            }
            
            if(email.isEmpty())
            {
                error1.setText("Email required");
                hr=true;
            }
            else
            {
                
                if(!email.endsWith("@gmail.com"))
                {
                    error1.setText("Gmail account required (e.g \"@gmail.com\")");
                    hr=true;
                }
                else
                {
                    error1.setText("");
                }
                
            }
/*            boolean isTaken=false;
            try
            {
                Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgress","123");
                PreparedStatement stm = con.prepareStatement("Select from websitedatabase where username ?");
                stm.setString(1, username);
                ResultSet result = stm.executeQuery();
                if(result.next() && result.getInt(1)>0)
                {
                    isTaken=true;
                }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            return isTaken;*/

            if(state==null || state.isEmpty())
            {
                error6.setText("Choose your state");
                hr=true;
            }
            
            else
            {
                error6.setText("");
            }
            
            if(address.isEmpty())
            {
                error2.setText("Address required");
                hr=true;
            }
            else
            {
                error2.setText("");
            }
            
            if(sex==null || sex.isEmpty())
            {
                error5.setText("Gender required");
                hr=true;
            }
            
            else
            {
                error5.setText("");
            }
            
            if(username.isEmpty())
            {
                error3.setText("Username required");
                hr=true;
            }
            else if(username.contains(" "))
            {
                error3.setText("Username cannot contain spaces");
                hr=true;
            }
            else if(username.contains(".*\\s{2,}.*"))
            {
                error3.setText("Username cannot contain multiple spaces");
                hr=true;
            }
            else
            {
                error3.setText("");
            }
            
            if(password.isEmpty())
            {
                error4.setText("Password required");
                hr=true;
            }
            else
            {
                error4.setText("");
            }
            
            if(hr)
            {
                return;
            }  
            String dbUrl = System.getenv("DB_URL") != null ? System.getenv("DB_URL") : "jdbc:postgresql://localhost:5432/postgres";
            String dbUser = System.getenv("DB_USER") != null ? System.getenv("DB_USER") : "postgres";
            String dbPass = System.getenv("DB_PASS") != null ? System.getenv("DB_PASS") : "";
            Connection con = DriverManager.getConnection(dbUrl, dbUser, dbPass);
            PreparedStatement stm = con.prepareStatement("Insert into websitedatabase(name,email,password,address,sex,username,state)values(?,?,?,?,?,?,?)");
            stm.setString(1, name);
            stm.setString(2, email);
            stm.setString(3, password);
            stm.setString(4, address);
            stm.setString(5, sex);
            stm.setString(6, username);
            stm.setString(7, state);
            stm.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(this,"Registration Successful!!!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
            System.out.println("Error: "+ e);
        }
        
        LoginPage log = new LoginPage();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fusernameActionPerformed

    private void femailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femailActionPerformed

    private void fstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fstateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginPage login=new LoginPage();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel error;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JLabel error5;
    private javax.swing.JLabel error6;
    private javax.swing.JTextField faddress;
    private javax.swing.JTextField femail;
    private javax.swing.JComboBox<String> fgender;
    private javax.swing.JTextField fname;
    private javax.swing.JPasswordField fpass;
    private javax.swing.JComboBox<String> fstate;
    private javax.swing.JTextField fusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
